#!/bin/sh

echo "██╗      █████╗ ███╗   ███╗██████╗ ███████╗"
echo "██║     ██╔══██╗████╗ ████║██╔══██╗╚════██║"
echo "██║     ███████║██╔████╔██║██████╔╝    ██╔╝"
echo "██║     ██╔══██║██║╚██╔╝██║██╔═══╝    ██╔╝ "
echo "███████╗██║  ██║██║ ╚═╝ ██║██║        ██║  "
echo "╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝        ╚═╝  "


if [ ! -f /firstrun.txt ]
then
    echo "Preparing first start"
    usermod -u $UID www-data

    if [ ! -d /var/lib/mysql/mysql ]
    then
        echo "No Database found, copying default..."
        mv /var/lib/mysql.back/* /var/lib/mysql
        /etc/init.d/mysql start

        echo "setting up PhpMyAdmin"
        # Import database for for PhpMyAdmin
        mysql -u root < /usr/share/doc/phpmyadmin/examples/create_tables.sql

        # Setting up user for PhpMyAdmin
        echo "CREATE USER 'phpmyadmin'@'localhost' IDENTIFIED BY 'xbEDb39XsnOod331ca' ;" | mysql -u root
        echo "GRANT ALL ON phpmyadmin.* TO 'phpmyadmin'@'localhost' ;" | mysql -u root
        
        echo "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD' ;" | mysql -u root
        echo "CREATE DATABASE \`$MYSQL_DATABASE\` CHARACTER SET utf8 ;" | mysql -u root
        echo "GRANT ALL ON *.* TO '$MYSQL_USER'@'%' ;" | mysql -u root
        echo 'FLUSH PRIVILEGES ;' | mysql -u root

        chown -R www-data:www-data /var/www
    fi
fi

/etc/init.d/apache2 restart
/etc/init.d/mysql start

if [ ! -f /firstrun.txt ]
then
    touch /firstrun.txt



    if [ -f /var/lib/mysql/setup.sh ]
    then
        bash /var/lib/mysql/setup.sh
    fi
    echo "OK"
fi

if [ -f /var/lib/mysql/startup.sh ]
then
    bash /var/lib/mysql/startup.sh
fi

tail -f /var/log/apache2/error.log -f /var/log/apache2/access.log